<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-1D78PSH8" name="IntegratedMailViewTestCases.VerifyTashAllAccount" tests="5" failures="3" timestamp="20 Jul 2017 05:20:55 GMT" time="10.699" errors="1">
  <testcase name="testMoveToTrashAllAccount" time="5.245" classname="IntegratedMailViewTestCases.VerifyTashAllAccount"/>
  <testcase name="testDeleteForeverAllAccount" time="0.001" classname="IntegratedMailViewTestCases.VerifyTashAllAccount"/>
  <testcase name="testMovetoInboxOfTrashEmailAllAccount" time="5.453" classname="IntegratedMailViewTestCases.VerifyTashAllAccount">
    <error type="java.lang.AssertionError" message="Email moved to Inbox from Untrash List is unsucessfully expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Email moved to Inbox from Untrash List is unsucessfully expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at emailTestCases.VerifyTrash.testMoveToInboxFromTrashListing(VerifyTrash.java:72)
	at IntegratedMailViewTestCases.VerifyTashAllAccount.testMovetoInboxOfTrashEmailAllAccount(VerifyTashAllAccount.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- testMovetoInboxOfTrashEmailAllAccount -->
  <testcase name="testBatchMovetoInboxOfTrashAllAccount" time="0.000" classname="IntegratedMailViewTestCases.VerifyTashAllAccount"/>
  <testcase name="testBatchMoveToTrashAllAccount" time="0.000" classname="IntegratedMailViewTestCases.VerifyTashAllAccount"/>
</testsuite> <!-- IntegratedMailViewTestCases.VerifyTashAllAccount -->
